runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /app/js
  static_dir: app/js

- url: /signup
  script: main.app
  secure: always

- url: /login
  script: main.app
  secure: always

- url: /forgot
  script: main.app
  secure: always

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"